#define _(x) x

const char     *txt[] = {
/* actionclasses.cfg */
    _("Click and drag to move desktop\n(on any desktop but desktop 0)"),
    _("Switch desktops"),
    _("Go to the next desktop"),
    _("Switch desktops"),
    _("Go to the previous desktop"),
    _("Move"),
    _("Move this window"),
    _("Shade/unshade this window"),
    _("Show the Window Options menu"),
    _("Shade/unshade this window"),
    _("Show/hide group borders"),
    _("Start a group"),
    _("Add to current group"),
    _("Break this window's group"),
    _("Shade"),
    _("Unshade"),
    _("Resize"),
    _("Resize this window"),
    _("Move this window"),
    _("Resize horizontally"),
    _("Resize this window horizontally"),
    _("Move this window"),
    _("Resize vertically"),
    _("Resize this window vertically"),
    _("Move this window"),
    _("Close"),
    _("Close this window"),
    _("Forcibly destroy this window"),
    _("Maximize height"),
    _("Toggle between maximum screen height and normal height"),
    _("Maximize width"),
    _("Toggle between maximum screen width and normal width"),
    _("Maximize"),
    _("Toggle between maximum screen size and normal size"),
    _("Toggle between maximum screen width and normal width"),
    _("Toggle between maximum screen height and normal height"),
    _("Send to another desktop"),
    _("Send this window to the next desktop"),
    _("Send to another desktop"),
    _("Send this window to the previous desktop"),
    _("Snapshot"),
    _("This button does nothing interesting"),
    _("Shade/unshade"),
    _("Shade/unshade this window"),
    _("Window Options"),
    _("Show the Window Options menu"),
    _("Iconify"),
    _("Iconify (Minimize) this window."),
    _("Show the Window Options menu"),
    _("More buttons"),
    _("Show more buttons"),
    _("Raise"),
    _("Raise this window to the top"),
    _("Lower"),
    _("Lower this window"),
    _("Stick/unstick"),
    _("Toggle the Omnipresent (visible on all Desktops) state of this window."),
/* bindings.cfg */
    _("Clicking your mouse on the desktop will perform\nthe following actions"),
    _("Display User menus"),
    _("Display Enlightenment menu"),
    _("Display Settings menu"),
    _("Display Enlightenment menu"),
    _("Display Task List menu"),
    _("Display Desktop menu"),
    _("Display Group menu"),
    _("Display Settings menu"),
    _("Go back a desktop"),
    _("Go forward a desktop"),
/* fonts.pango.cfg */
/* fonts.xft.cfg */
/* matches.cfg */
/* desktop.menu */
    _("Desktop Operations"),
    _("Backgrounds"),
    _("Cleanup desktop"),
    _("Goto next desktop"),
    _("Goto previous desktop"),
    _("Create new iconbox"),
    _("Create systray"),
    _("Show magnifier"),
/* maintenance.menu */
    _("Maintenance"),
    _("Purge config file cache"),
    _("Purge pager background cache"),
    _("Purge background selector cache"),
    _("Purge all caches"),
    _("Query config file cache usage"),
    _("Query pager background cache usage"),
    _("Query background selector cache usage"),
    _("Query all cache usage"),
    _("Regenerate menus"),
/* settings.menu */
    _("Settings"),
    _("Settings"),
    _("Desktop"),
    _("Themes"),
    _("Maintenance"),
    _("About Enlightenment"),
    _("About this theme"),
    _("Theme menu"),
    _("Restart"),
    _("Log out"),
    _("Shut down"),
/* winops.menu */
    _("Window Options"),
    _("Close"),
    _("Annihilate"),
    _("Iconify"),
    _("Leave alone"),
    _("Raise"),
    _("Lower"),
    _("Shade/unshade"),
    _("Stick/unstick"),
    _("Remember..."),
    _("Window size"),
    _("Set stacking"),
    _("Set border style"),
    _("Window groups"),
    _("Opacity"),
    _("Miscellaneous"),
/* winops_groups.menu */
    _("Groups"),
    _("Configure this window's group(s)"),
    _("Start a new group"),
    _("Add this window to the current group"),
    _("Select group to add this window to"),
    _("Remove this window from a group"),
    _("Destroy a group this window belongs to"),
/* winops_layer.menu */
    _("Stacking"),
    _("Lowest"),
    _("Below"),
    _("Normal"),
    _("Above"),
    _("Highest"),
/* winops_misc.menu */
    _("Miscellaneous"),
    _("Toggle skip window lists"),
    _("Toggle fixed position"),
    _("Toggle fixed size"),
    _("Toggle never focus"),
    _("Toggle click to focus"),
    _("Toggle never use area"),
    _("Toggle ignore arrange"),
    _("Toggle button grabs"),
    _("Toggle autoshade"),
    _("Toggle pass pointer"),
/* winops_opacity.menu */
    _("Opacity"),
    _("Default"),
    _("20%"),
    _("40%"),
    _("60%"),
    _("80%"),
    _("100%"),
    _("Focused opacity 100%"),
    _("Focused opacity follows unfocused"),
    _("Toggle fading"),
    _("Toggle shadows"),
/* winops_size.menu */
    _("Size"),
    _("Toggle max size"),
    _("Toggle max size - available"),
    _("Toggle max size - absolute"),
    _("Span Xinerama screens"),
    _("Toggle max height"),
    _("Toggle max height available"),
    _("Toggle max height absolute"),
    _("Toggle max width"),
    _("Toggle max width available"),
    _("Toggle max width absolute"),
    _("Toggle fullscreen"),
    _("Toggle zoom"),

    _("User menus"),
    _("User application list"),
    _("Applications"),
    _("Epplets"),
    _("Restart"),
    _("Log out"),
    _("Help"),
};
